[31m[1mERROR   [0m juju.client.connection:jasyncio.py:53 Task tmp raised an exception: cannot reuse already awaited coroutine
Traceback (most recent call last):
  File "/home/ubuntu/actions-runner/_work/test-runners-2-is-arm64-postgresql-operator/test-runners-2-is-arm64-postgresql-operator/.tox/integration/lib/python3.10/site-packages/juju/jasyncio.py", line 41, in _task_result_exp_handler
    task.result()
RuntimeError: cannot reuse already awaited coroutine
[32mINFO    [0m integration.ha_tests.test_async_replication:test_async_replication.py:86 Destroying second model
[33mWARNING [0m juju.client.connection:connection.py:654 RPC: Connection closed, reconnecting
[31m[1mERROR   [0m juju.client.connection:connection.py:662 RPC: Automatic reconnect failed
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.4.4    unsupported  01:51:09Z

App              Version  Status   Scale  Charm            Channel      Rev  Exposed  Message
data-integrator           waiting    0/1  data-integrator  latest/edge   40  no       waiting for machine
postgresql                waiting    0/3  postgresql                      0  no       waiting for machine

Unit               Workload  Agent       Machine  Public address  Ports  Message
data-integrator/0  waiting   allocating  3                               waiting for machine
postgresql/0       waiting   allocating  0                               waiting for machine
postgresql/1       waiting   allocating  1                               waiting for machine
postgresql/2       waiting   allocating  2                               waiting for machine

Machine  State    Address  Inst id  Base          AZ  Message
0        pending           pending  ubuntu@22.04      Creating container
1        pending           pending  ubuntu@22.04      Creating container
2        pending           pending  ubuntu@22.04      Creating container
3        pending           pending  ubuntu@22.04      Creating container

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

controller-0: 01:50:46 ERROR juju.worker.provisioner worker 0: shutting down pool due to error while handling a "start-instance 1" task: catacomb 0x4000050be0 is dying
controller-0: 01:50:46 ERROR juju.worker.provisioner worker 6: shutting down pool due to error while handling a "start-instance 0" task: catacomb 0x4000050be0 is dying
controller-0: 01:50:46 ERROR juju.worker.provisioner worker 1: shutting down pool due to error while handling a "start-instance 2" task: catacomb 0x4000050be0 is dying
controller-0: 01:50:46 ERROR juju.worker.provisioner worker 2: shutting down pool due to error while handling a "start-instance 3" task: catacomb 0x4000050be0 is dying

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...